cifar10-autoattack-20220217.sh: line 136: /home/xieyi/anaconda3/envs/mmat/bin/python: Permission denied
cifar10-autoattack-20220217.sh: line 139: /home/xieyi/anaconda3/envs/mmat/bin/python: Permission denied
cifar10-autoattack-20220217.sh: line 142: /home/xieyi/anaconda3/envs/mmat/bin/python: Permission denied
cifar10-autoattack-20220217.sh: line 145: /home/xieyi/anaconda3/envs/mmat/bin/python: Permission denied
cifar10-autoattack-20220217.sh: line 148: /home/xieyi/anaconda3/envs/mmat/bin/python: Permission denied
