

---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00000
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
cle_w_test.shape: torch.Size([10000, 8, 512])
cle_y_test.shape: torch.Size([10000, 8])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
generating latent adversarial examples...
Traceback (most recent call last):
  File "tasklauncher-20211008.py", line 135, in <module>
    adv_x_test, adv_y_test = latent_attacker.generatelatentadv(exp_result_dir, cle_test_dataloader, cle_w_test, cle_y_test, gan_net)
  File "/home/maggie/mmat/attacks/advattack.py", line 271, in generatelatentadv
    adv_w_test = self._attacker.perturb(cle_w_test, cle_y_test)         
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/advertorch/attacks/one_step_gradient.py", line 64, in perturb
    outputs = self.predict(xadv)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 479, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 406, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 308, in forward
  File "/home/maggie/mmat/utils/stylegan2ada/torch_utils/misc.py", line 102, in decorator
    return fn(*args, **kwargs)
  File "<string>", line 64, in modulated_conv2d
RuntimeError: CUDA out of memory. Tried to allocate 87.89 GiB (GPU 0; 10.76 GiB total capacity; 809.22 MiB already allocated; 8.76 GiB free; 924.00 MiB reserved in total by PyTorch)


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00001
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
cle_w_test.shape: torch.Size([1000, 8, 512])
cle_y_test.shape: torch.Size([1000, 8])
cle_w_test[:10]: tensor([[[-1.1945, -1.0594,  0.7946,  ..., -2.5003,  0.7963, -1.4156],
         [-1.1945, -1.0594,  0.7946,  ..., -2.5003,  0.7963, -1.4156],
         [-1.1945, -1.0594,  0.7946,  ..., -2.5003,  0.7963, -1.4156],
         ...,
         [-1.1945, -1.0594,  0.7946,  ..., -2.5003,  0.7963, -1.4156],
         [-1.1945, -1.0594,  0.7946,  ..., -2.5003,  0.7963, -1.4156],
         [-1.1945, -1.0594,  0.7946,  ..., -2.5003,  0.7963, -1.4156]],

        [[ 0.1516,  3.0958,  0.3547,  ..., -1.2618,  2.2712,  1.4038],
         [ 0.1516,  3.0958,  0.3547,  ..., -1.2618,  2.2712,  1.4038],
         [ 0.1516,  3.0958,  0.3547,  ..., -1.2618,  2.2712,  1.4038],
         ...,
         [ 0.1516,  3.0958,  0.3547,  ..., -1.2618,  2.2712,  1.4038],
         [ 0.1516,  3.0958,  0.3547,  ..., -1.2618,  2.2712,  1.4038],
         [ 0.1516,  3.0958,  0.3547,  ..., -1.2618,  2.2712,  1.4038]]])
cle_y_test[:10]: tensor([6, 9])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
generating latent adversarial examples...
Traceback (most recent call last):
  File "tasklauncher-20211008.py", line 135, in <module>
    adv_x_test, adv_y_test = latent_attacker.generatelatentadv(exp_result_dir, cle_test_dataloader, cle_w_test, cle_y_test, gan_net)
  File "/home/maggie/mmat/attacks/advattack.py", line 271, in generatelatentadv
    adv_w_test = self._attacker.perturb(cle_w_test, cle_y_test)         
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/advertorch/attacks/one_step_gradient.py", line 64, in perturb
    outputs = self.predict(xadv)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 479, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 406, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 308, in forward
  File "/home/maggie/mmat/utils/stylegan2ada/torch_utils/misc.py", line 102, in decorator
    return fn(*args, **kwargs)
  File "<string>", line 66, in modulated_conv2d
RuntimeError: CUDA out of memory. Tried to allocate 8.79 GiB (GPU 0; 10.76 GiB total capacity; 9.01 GiB already allocated; 444.12 MiB free; 9.23 GiB reserved in total by PyTorch)


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00002
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
generating latent adversarial examples...
cle_w_test.shape: torch.Size([256, 8, 512])
cle_y_test.shape: torch.Size([256])
Setting up PyTorch plugin "bias_act_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Traceback (most recent call last):
  File "tasklauncher-20211008.py", line 135, in <module>
    adv_x_test, adv_y_test = latent_attacker.generatelatentadv(exp_result_dir, cle_test_dataloader, cle_w_test, cle_y_test, gan_net)
  File "/home/maggie/mmat/attacks/advattack.py", line 275, in generatelatentadv
    adv_w_test = self._attacker.perturb(cle_w_test, cle_y_test)         
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/advertorch/attacks/one_step_gradient.py", line 64, in perturb
    outputs = self.predict(xadv)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 479, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 414, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 308, in forward
  File "/home/maggie/mmat/utils/stylegan2ada/torch_utils/misc.py", line 102, in decorator
    return fn(*args, **kwargs)
  File "<string>", line 66, in modulated_conv2d
RuntimeError: CUDA out of memory. Tried to allocate 2.25 GiB (GPU 0; 10.76 GiB total capacity; 9.25 GiB already allocated; 210.12 MiB free; 9.45 GiB reserved in total by PyTorch)


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00003
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
generating latent adversarial examples...
cle_w_test.shape: torch.Size([128, 8, 512])
cle_y_test.shape: torch.Size([128])
Setting up PyTorch plugin "bias_act_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Traceback (most recent call last):
  File "tasklauncher-20211008.py", line 135, in <module>
    adv_x_test, adv_y_test = latent_attacker.generatelatentadv(exp_result_dir, cle_test_dataloader, cle_w_test, cle_y_test, gan_net)
  File "/home/maggie/mmat/attacks/advattack.py", line 275, in generatelatentadv
    adv_w_test = self._attacker.perturb(cle_w_test, cle_y_test)         
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/advertorch/attacks/one_step_gradient.py", line 64, in perturb
    outputs = self.predict(xadv)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 479, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 413, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 308, in forward
  File "/home/maggie/mmat/utils/stylegan2ada/torch_utils/misc.py", line 102, in decorator
    return fn(*args, **kwargs)
  File "<string>", line 66, in modulated_conv2d
RuntimeError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 10.76 GiB total capacity; 8.37 GiB already allocated; 202.12 MiB free; 9.45 GiB reserved in total by PyTorch)


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00004
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
generating latent adversarial examples...
cle_w_test.shape: torch.Size([128, 8, 512])
cle_y_test.shape: torch.Size([128])
Setting up PyTorch plugin "bias_act_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Traceback (most recent call last):
  File "tasklauncher-20211008.py", line 135, in <module>
    adv_x_test, adv_y_test = latent_attacker.generatelatentadv(exp_result_dir, cle_test_dataloader, cle_w_test, cle_y_test, gan_net)
  File "/home/maggie/mmat/attacks/advattack.py", line 275, in generatelatentadv
    adv_w_test = self._attacker.perturb(cle_w_test, cle_y_test)         
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/advertorch/attacks/one_step_gradient.py", line 64, in perturb
    outputs = self.predict(xadv)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 479, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 413, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 308, in forward
  File "/home/maggie/mmat/utils/stylegan2ada/torch_utils/misc.py", line 102, in decorator
    return fn(*args, **kwargs)
  File "<string>", line 66, in modulated_conv2d
RuntimeError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 10.76 GiB total capacity; 8.37 GiB already allocated; 202.12 MiB free; 9.45 GiB reserved in total by PyTorch)


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00005
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
generating latent adversarial examples...
cle_w_test.shape: torch.Size([64, 8, 512])
cle_y_test.shape: torch.Size([64])
Setting up PyTorch plugin "bias_act_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
adv_x_test.shape: torch.Size([64, 3, 32, 32])
adv_y_test.shape: torch.Size([64])
finished generate latent adversarial examples !
Saving cifar10 testset  adversarial examples...
adv_x_test.shape: torch.Size([64, 3, 32, 32])
adv_y_test.shape: torch.Size([64])
standard trained classifier accuary on adversarial testset:46.8750%
standard trained classifier loss on adversarial testset:2.439861297607422
cle_x_test.shape: torch.Size([64, 3, 32, 32])
cle_y_test.shape: torch.Size([64])
standard trained classifier accuary on clean testset:90.6250%
standard trained classifier loss on clean testset:0.40173935890197754
---------------------------------------




---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00006
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
cle_w_test.shape: torch.Size([10000, 8, 512])
cle_y_test.shape: torch.Size([10000])
testset_total_num: 10000
batch_size: 68
batch_num: 148
Setting up PyTorch plugin "bias_act_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Traceback (most recent call last):
  File "tasklauncher-20211008.py", line 135, in <module>
    adv_x_test, adv_y_test = latent_attacker.generatelatentadv(exp_result_dir, cle_test_dataloader, cle_w_test, cle_y_test, gan_net)
  File "/home/maggie/mmat/attacks/advattack.py", line 287, in generatelatentadv
    adv_w_test = torch.stack(adv_w_test)
RuntimeError: stack expects each tensor to be equal size, but got [68, 8, 512] at entry 0 and [4, 8, 512] at entry 147


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00007
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
cle_w_test.shape: torch.Size([10000, 8, 512])
cle_y_test.shape: torch.Size([10000])
testset_total_num: 10000
batch_size: 64
batch_num: 157
Setting up PyTorch plugin "bias_act_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
adv_w_test.shape: torch.Size([10000, 8, 512])
Traceback (most recent call last):
  File "tasklauncher-20211008.py", line 135, in <module>
    adv_x_test, adv_y_test = latent_attacker.generatelatentadv(exp_result_dir, cle_test_dataloader, cle_w_test, cle_y_test, gan_net)
  File "/home/maggie/mmat/attacks/advattack.py", line 291, in generatelatentadv
    adv_x_test = gan_net(adv_w_test)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 479, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 406, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 308, in forward
  File "/home/maggie/mmat/utils/stylegan2ada/torch_utils/misc.py", line 102, in decorator
    return fn(*args, **kwargs)
  File "<string>", line 64, in modulated_conv2d
RuntimeError: CUDA out of memory. Tried to allocate 87.89 GiB (GPU 0; 10.76 GiB total capacity; 815.52 MiB already allocated; 8.63 GiB free; 1.01 GiB reserved in total by PyTorch)


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00008
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
cle_w_test.shape: torch.Size([10000, 8, 512])
cle_y_test.shape: torch.Size([10000])
testset_total_num: 10000
batch_size: 64
batch_num: 157
Setting up PyTorch plugin "bias_act_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
adv_x_test.shape: torch.Size([10000, 3, 32, 32])
adv_x_test.shape: torch.Size([10000, 3, 32, 32])
adv_y_test.shape: torch.Size([10000])
finished generate latent adversarial examples !
Saving cifar10 testset  adversarial examples...
adv_x_test.shape: torch.Size([10000, 3, 32, 32])
adv_y_test.shape: torch.Size([10000])
standard trained classifier accuary on adversarial testset:47.9300%
standard trained classifier loss on adversarial testset:2.6106364727020264
Traceback (most recent call last):
  File "tasklauncher-20211008.py", line 151, in <module>
    cle_x_test = gan_net(cle_w_test.cuda())
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 479, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 406, in forward
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<string>", line 308, in forward
  File "/home/maggie/mmat/utils/stylegan2ada/torch_utils/misc.py", line 102, in decorator
    return fn(*args, **kwargs)
  File "<string>", line 64, in modulated_conv2d
RuntimeError: CUDA out of memory. Tried to allocate 87.89 GiB (GPU 0; 10.76 GiB total capacity; 776.21 MiB already allocated; 8.63 GiB free; 1.01 GiB reserved in total by PyTorch)


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20211008
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/fgsm/alexnet-cifar10/20211008/00009
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
latent adversarial attack.............
initlize classifier
learned calssify model != None
cle_w_test.shape: torch.Size([25397, 8, 512])
cle_y_test.shape: torch.Size([25397, 8])
initlize attack classifier
generate latent adversarial exampels
latent fgsm attack
eps： 0.05
cle_w_test.shape: torch.Size([10000, 8, 512])
cle_y_test.shape: torch.Size([10000])
testset_total_num: 10000
batch_size: 64
batch_num: 157
batch_index: 0
Setting up PyTorch plugin "bias_act_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... /home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/utils/cpp_extension.py:286: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Done.
batch_index: 1
batch_index: 2
batch_index: 3
batch_index: 4
batch_index: 5
batch_index: 6
batch_index: 7
batch_index: 8
batch_index: 9
batch_index: 10
batch_index: 11
batch_index: 12
batch_index: 13
batch_index: 14
batch_index: 15
batch_index: 16
batch_index: 17
batch_index: 18
batch_index: 19
batch_index: 20
batch_index: 21
batch_index: 22
batch_index: 23
batch_index: 24
batch_index: 25
batch_index: 26
batch_index: 27
batch_index: 28
batch_index: 29
batch_index: 30
batch_index: 31
batch_index: 32
batch_index: 33
batch_index: 34
batch_index: 35
batch_index: 36
batch_index: 37
batch_index: 38
batch_index: 39
batch_index: 40
batch_index: 41
batch_index: 42
batch_index: 43
batch_index: 44
batch_index: 45
batch_index: 46
batch_index: 47
batch_index: 48
batch_index: 49
batch_index: 50
batch_index: 51
batch_index: 52
batch_index: 53
batch_index: 54
batch_index: 55
batch_index: 56
batch_index: 57
batch_index: 58
batch_index: 59
batch_index: 60
batch_index: 61
batch_index: 62
batch_index: 63
batch_index: 64
batch_index: 65
batch_index: 66
batch_index: 67
batch_index: 68
batch_index: 69
batch_index: 70
batch_index: 71
batch_index: 72
batch_index: 73
batch_index: 74
batch_index: 75
batch_index: 76
batch_index: 77
batch_index: 78
batch_index: 79
batch_index: 80
batch_index: 81
batch_index: 82
batch_index: 83
batch_index: 84
batch_index: 85
batch_index: 86
batch_index: 87
batch_index: 88
batch_index: 89
batch_index: 90
batch_index: 91
batch_index: 92
batch_index: 93
batch_index: 94
batch_index: 95
batch_index: 96
batch_index: 97
batch_index: 98
batch_index: 99
batch_index: 100
batch_index: 101
batch_index: 102
batch_index: 103
batch_index: 104
batch_index: 105
batch_index: 106
batch_index: 107
batch_index: 108
batch_index: 109
batch_index: 110
batch_index: 111
batch_index: 112
batch_index: 113
batch_index: 114
batch_index: 115
batch_index: 116
batch_index: 117
batch_index: 118
batch_index: 119
batch_index: 120
batch_index: 121
batch_index: 122
batch_index: 123
batch_index: 124
batch_index: 125
batch_index: 126
batch_index: 127
batch_index: 128
batch_index: 129
batch_index: 130
batch_index: 131
batch_index: 132
batch_index: 133
batch_index: 134
batch_index: 135
batch_index: 136
batch_index: 137
batch_index: 138
batch_index: 139
batch_index: 140
batch_index: 141
batch_index: 142
batch_index: 143
batch_index: 144
batch_index: 145
batch_index: 146
batch_index: 147
batch_index: 148
batch_index: 149
batch_index: 150
batch_index: 151
batch_index: 152
batch_index: 153
batch_index: 154
batch_index: 155
batch_index: 156
adv_x_test.shape: torch.Size([10000, 3, 32, 32])
adv_x_test.shape: torch.Size([10000, 3, 32, 32])
adv_y_test.shape: torch.Size([10000])
finished generate latent adversarial examples !
Saving cifar10 testset  adversarial examples...
adv_x_test.shape: torch.Size([10000, 3, 32, 32])
adv_y_test.shape: torch.Size([10000])
standard trained classifier accuary on adversarial testset:48.1100%
standard trained classifier loss on adversarial testset:2.619767904281616
cle_x_test.shape: torch.Size([10000, 3, 32, 32])
cle_y_test.shape: torch.Size([10000])
standard trained classifier accuary on clean testset:83.1600%
standard trained classifier loss on clean testset:0.6153902411460876
---------------------------------------


