

---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20220219
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/autoattack/resnet50-cifar10/20220219/00000
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
eps: 0.02
pixel adversarial attack.............
Traceback (most recent call last):
  File "tasklauncher-20220218.py", line 63, in <module>
    learned_model = torch.load(args.cla_network_pkl)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/maggie/mmat/result/train/cla-train/resnet50-cifar10/20210908/00001-testacc-0.7666/train-cifar10-dataset/standard-trained-classifier-resnet50-on-clean-cifar10-epoch-0011.pkl'


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20220219
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/autoattack/resnet50-cifar10/20220219/00001
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
eps: 0.05
pixel adversarial attack.............
Traceback (most recent call last):
  File "tasklauncher-20220218.py", line 63, in <module>
    learned_model = torch.load(args.cla_network_pkl)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/maggie/mmat/result/train/cla-train/resnet50-cifar10/20210908/00001-testacc-0.7666/train-cifar10-dataset/standard-trained-classifier-resnet50-on-clean-cifar10-epoch-0011.pkl'


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20220219
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/autoattack/resnet50-cifar10/20220219/00002
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
eps: 0.1
pixel adversarial attack.............
Traceback (most recent call last):
  File "tasklauncher-20220218.py", line 63, in <module>
    learned_model = torch.load(args.cla_network_pkl)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/maggie/mmat/result/train/cla-train/resnet50-cifar10/20210908/00001-testacc-0.7666/train-cifar10-dataset/standard-trained-classifier-resnet50-on-clean-cifar10-epoch-0011.pkl'


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20220219
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/autoattack/resnet50-cifar10/20220219/00003
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
eps: 0.2
pixel adversarial attack.............
Traceback (most recent call last):
  File "tasklauncher-20220218.py", line 63, in <module>
    learned_model = torch.load(args.cla_network_pkl)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/maggie/mmat/result/train/cla-train/resnet50-cifar10/20210908/00001-testacc-0.7666/train-cifar10-dataset/standard-trained-classifier-resnet50-on-clean-cifar10-epoch-0011.pkl'


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20220219
whitebox attack
Experiment result save dir: /home/maggie/mmat/result/attack/autoattack/resnet50-cifar10/20220219/00004
initilize the dataset loading parameters
load cifar10 dataset
Loading *cifar10* train dataloader finished !
Loading *cifar10* test dataloader finished !
eps: 0.3
pixel adversarial attack.............
Traceback (most recent call last):
  File "tasklauncher-20220218.py", line 63, in <module>
    learned_model = torch.load(args.cla_network_pkl)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xieyi/anaconda3/envs/mmat/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/maggie/mmat/result/train/cla-train/resnet50-cifar10/20210908/00001-testacc-0.7666/train-cifar10-dataset/standard-trained-classifier-resnet50-on-clean-cifar10-epoch-0011.pkl'
