s: command not found


---------------------------------------
Torch cuda is available
usage: tasklauncher-20210919.py [-h] {load,run} ...
tasklauncher-20210919.py: error: unrecognized arguments: â€“epochs 20


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20210919
Experiment result save dir: /home/maggie/mmat/result/defense/mmat/fgsm/basemixup-uniformsampler/resnet18-kmnist/20210919/00000
initilize the dataset loading parameters
Loading *kmnist* train dataloader finished !
Loading *kmnist* test dataloader finished !
initlize classifier
learned calssify model != None
standard trained classifier *accuary* on adversarial testset:81.0600%
standard trained classifier *accuary* on clean testset:97.3200%
Traceback (most recent call last):
  File "tasklauncher-20210919.py", line 165, in <module>
    raise error
TypeError: exceptions must derive from BaseException


---------------------------------------
Torch cuda is available
args.subcommand=run, run the command line
date: 20210919
Experiment result save dir: /home/maggie/mmat/result/defense/mmat/fgsm/basemixup-uniformsampler/resnet18-kmnist/20210919/00001
initilize the dataset loading parameters
Loading *kmnist* train dataloader finished !
Loading *kmnist* test dataloader finished !
initlize classifier
learned calssify model != None
standard trained classifier *accuary* on adversarial testset:81.0600%
standard trained classifier *accuary* on clean testset:97.3200%
Traceback (most recent call last):
  File "tasklauncher-20210919.py", line 165, in <module>
    raise error
TypeError: exceptions must derive from BaseException
